name = "your-website"
type = "webpack"
account_id = "<your-cloudflare-account-id>"
workers_dev = false

[site]
bucket = "./public"
entry-point = "workers-site"

[env.production]
name = "your-website"
route = "your-website.example.com"
zone_id = "<your-cloudflare-zone-id>"